app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:4173"

spring:
  profiles:
    active: dev
  main:
      banner-mode: "off"
  application:
    name: springboot-jwt-graphql
  graphql:
    path: /graphql
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://kv-fruitly.vault.azure.net/

  datasource:
    url: jdbc:postgresql://ep-divine-grass-a2mcujmz-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: ${spring-datasource-username} # Maps to KV secret
    password: ${spring-datasource-password} # Maps to KV secret
    driver-class-name: org.postgresql.Driver

    # Hikari connection pool tuning
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      # For production, consider "validate" instead of "update"
      ddl-auto: update
    show-sql: false        # set true if you want to debug queries
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

jwt:
  secret-key: ${jwt-secret-key} # Maps to KV secret
  # Access token expiration time in milliseconds (e.g., 1 day)
  expiration: 86400000 
  refreshExpirationMs: 604800000  # 7 days in milliseconds

# Optional: logging configuration for Hibernate SQL
logging:
  level:
    root: ERROR
    com.example: INFO
    org.springframework.security: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html