name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 24
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # 3. Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Run tests
      - name: Run tests
        run: mvn test

      # 5. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t springboot-jwt-graphql:latest .

      # 7. (Optional) Push to Docker Hub
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #
      #- name: Push Docker image
      #  run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-jwt-graphql:latest
